export const networkWifi = [
  {
    image: "/get-services/network-wifi/ethernet.svg",
    name: "Ethernet/WiFi network support",
    features: [
      "Make sure modem/router/switch is/are connected",
      "Verify configuration and updates",
      "Troubleshoot connectivity issues",
      "Internet speed test",
      "Password and Access recovery",
      "Advise on necessary repair or upgrade",
    ],
    durationicon: "/get-services/network-wifi/ethernet-duration.svg",
    priceicon: "/get-services/network-wifi/ethernet-price.svg",
  },
  {
    image: "/get-services/network-wifi/on-site.svg",
    name: "Cell Signal Boosting",
    features: [
      "Inspection of existing LAN cabling and WiFi coverage",
      "Visual inspection for any potential barriers that may affect the network performance",
      "Identify user arreas",
      "Determine initial wired and wireless access point locations",
      "Document findings",
    ],
    durationicon: "/get-services/network-wifi/on-site-duration.svg",
    priceicon: "/get-services/network-wifi/on-site-price.svg",
  },
  {
    image: "/get-services/network-wifi/cell-signal.svg",
    name: "On-Site Survey",
    features: [
      "Cell signal booster installation for AT&T, Verizon, T-Mobile, US Cellular, and Straight Talk",
      "Determine the closest cell tower location",
      "Determine antennas and other equipment installation location",
      "Aiming outdoor antenna to the best signal level from your carrier",
      "Post-install equipment setup",
      "Dedicated local support",
      "No subscription fees",
      "Quantity discount is available",
    ],
    durationicon: "/get-services/network-wifi/cell-signal-duration.svg",
    priceicon: "/get-services/network-wifi/cell-signal-price.svg",
  },
  {
    image: "/get-services/network-wifi/large-area-wifi.svg",
    name: "Large area WiFi network design",
    features: [
      "Conduct a site survey",
      "Visual inspection for any potential barriers that may affect the network performance",
      "Identify user areas",
      "Locating sites and installing WiFi units",
      "Determining Equipment Needed",
      "Run a predictive survey to estimate expected coverage",
      "Document findings",
    ],
    durationicon: "/get-services/network-wifi/large-area-wifi-duration.svg",
    priceicon: "/get-services/network-wifi/large-area-wifi-price.svg",
  },
  {
    image: "/get-services/network-wifi/smart-wifi.svg",
    name: "Smart WiFi",
    features: [
      "3 Wireless Access Points (APs) Installation",
      "Determine an equipment installation location",
      "Run Internet cable to each AP",
      "Post-install equipment setup",
      "Dedicated local support",
      "No subscription fees",
      "Quantity discount is available",
    ],
    durationicon: "/get-services/network-wifi/smart-wifi-duration.svg",
    priceicon: "/get-services/network-wifi/smart-wifi-price.svg",
  },
  {
    image: "/get-services/network-wifi/smart-wifi.svg",
    name: "Wiring & Prewiring",
    features: [
      "Wire/cable run inside of wall passing one floor",
      "Define wire/cable passway and wall plates location",
      "Provide possible pitfalls before starting a job",
      "Label and terminate the cable",
      "Test connection status",
      "Additional charges may apply to patch the wall/ceiling during the service if any",
      "Quantity discount is available",
    ],
    durationicon: "/get-services/network-wifi/smart-wifi-duration.svg",
    priceicon: "/get-services/network-wifi/smart-wifi-price.svg",
  },
];

export const smartHome = [
  {
    image: "/get-services/smart-home/complete-smart.svg",
    name: "Complete Smart Technology Design",
    features: [
      "Determine the smart home automation system that is best for you",
      "Create your project specification including features and functionality for each part of your residence",
      "Examine built-in smart tech solutions for your renovation or remodeling",
      "Design the smart system to interact with your existing HVAC, lighting, security, internet network, etc and/or upgrade/install to the latest tech",
      "Design cost is deducted from the project cost estimate",
      "LOXONE Smart Automation",
    ],
    durationicon: "/get-services/smart-home/complete-smart-duration.svg",
    priceicon: "/get-services/smart-home/complete-smart-price.svg",
  },
];

export const entertainment = [
  {
    image: "/get-services/entertainment/home-theater.svg",
    name: "Home Theater Room Design",
    features: [
      "On-Site consultation with trained design and tech consultants",
      "Evaluation of your needs",
      "Understand your style and vision",
      "Basic suggestions for improvement",
      "Identify your entertainment",
      "Define the next steps of your project",
      "Design cost is deducted from the project cost estimate",
    ],
    durationicon: "/get-services/entertainment/home-theater-duration.svg",
    priceicon: "/get-services/entertainment/home-theater-price.svg",
  },
  {
    name: "Media Room Design",
    features: [
      "On-Site consultation with trained design and tech consultants",
      "Evaluation of your needs",
      "Understand your style and vision",
      "Basic suggestions for improvement",
      "Identify your entertainment",
      "Define the next steps of your project",
      "Design cost is deducted from the project cost estimate",
    ],
    durationicon: "/get-services/entertainment/media-room-duration.svg",
    priceicon: "/get-services/entertainment/media-room-price.svg",
  },
  {
    name: "Entertainment Room Design",
    features: [
      "On-Site consultation with trained design and tech consultants",
      "Evaluation of your needs",
      "Understand your style and vision",
      "Basic suggestions for improvement",
      "Identify your entertainment",
      "Define the next steps of your project",
      "Design cost is deducted from the project cost estimate",
    ],
    durationicon: "/get-services/entertainment/entertainment-room-duration.svg",
    priceicon: "/get-services/entertainment/entertainment-room-price.svg",
  },
  {
    name: "Whole Home Audio System Design",
    features: [
      "On-Site consultation with trained design and tech consultants",
      "Evaluation of your needs",
      "Understand your style and vision",
      "Basic suggestions for improvement",
      "Identify your entertainment",
      "Define the next steps of your project",
      "Design cost is deducted from the project cost estimate",
    ],
    durationicon: "/get-services/entertainment/whole-home-duration.svg",
    priceicon: "/get-services/entertainment/whole-home-price.svg",
  },
  {
    name: "Remodeling Design with built-in tech",
    features: [
      "On-Site consultation with trained design and tech consultants",
      "Evaluation of your needs",
      "Understand your style and vision",
      "Basic suggestions for improvement",
      "Identify your entertainment",
      "Define the next steps of your project",
      "Design cost is deducted from the project cost estimate",
    ],
    durationicon: "/get-services/entertainment/remodeling-duration.svg",
    priceicon: "/get-services/entertainment/remodeling-price.svg",
  },
  {
    name: "RGBW design",
    features: [
      "On-Site consultation with trained design and tech consultants",
      "Evaluation of your needs",
      "Understand your style and vision",
      "Basic suggestions for improvement",
      "Identify your entertainment",
      "Define the next steps of your project",
      "Design cost is deducted from the project cost estimate",
    ],
    durationicon: "/get-services/entertainment/rgbw-duration.svg",
    priceicon: "/get-services/entertainment/rgbw-price.svg",
  },
];

export const homeTheater = [
  {
    name: "Home Theater and Sound System Setup",
    features: [
      "Connect Video and Audio components in one location",
      "Connect speakers, installation speakers and prewiring is an additional cost",
      "Basic AV settings and Internet/WiFi connectivity setup",
      "Remote setup, universal remote like Logitech Harmony setup is an additional $ 99",
      "Set-up a mobile app if applicable",
    ],
    durationicon: "/get-services/home-theater/home-theater-duration.svg",
    priceicon: "/get-services/home-theater/home-theater-price.svg",
  },
  {
    name: "On-wall 5 surround speakers mounting",
    features: [
      "Determine speakers' locations",
      "Mount speakers (speaker wall mounts are not included)",
      "Connect speaker wires to speakers ",
      "On-wall speaker pre-wiring with cord covers is an additional $89 for each speaker (wire and cord covers are not included)",
      "In-wall speaker pre-wiring is an additional $299 per speaker (wire is not included, additional charges may apply to fix trim and finishing)",
    ],
    durationicon: "/get-services/home-theater/on-wall-duration.svg",
    priceicon: "/get-services/home-theater/on-wall-price.svg",
  },
  {
    name: "On-wall 7 surround speakers mounting",
    features: [
      "Determine speakers' locations",
      "Mount speakers (speaker wall mounts are not included)",
      "Connect speaker wires to speakers ",
      "On-wall speaker pre-wiring with cord covers is an additional $89 for each speaker (wire and cord covers are not included)",
      "In-wall speaker pre-wiring is an additional $299 per speaker (wire is not included, additional charges may apply to fix trim and finishing)",
    ],
    durationicon: "/get-services/home-theater/on-wall-7-duration.svg",
    priceicon: "/get-services/home-theater/on-wall-7-price.svg",
  },
];

export const evTech = [
  {
    name: "Home EV Charger Installation",
    features: [
      "Consultation and Estimation",
      "Get a permit and handle necessary inspections ",
      "Verify your electrical panel can handle your charging station load ",
      "Provide solutions to improve power ampacity",
      "Install circuit breaker, run electrical cable, install EV charger",
      "Verify EV charger operation, completed app setup if applicable",
    ],
    durationicon: "/get-services/ev-tech/home-ev-duration.svg",
    priceicon: "/get-services/ev-tech/home-ev-price.svg",
  },
  {
    name: "Smart Home Ecosystem Design",
    features: [
      "Consultation",
      "Identify the preferences of your complete smart home ecosystem: solar, automation, and your car ",
      "Determine the smart home automation system that is best for you  ",
      "Create your project specification including features and functionality for each part of your residence ",
      "Examine built-in smart tech solutions for your renovation or remodeling",
      "Design the smart system to interact with your existing HVAC, lighting, security, internet network, etc and/or upgrade/install to the latest tech ",
      "Design cost is deducted from the project cost estimate",
    ],
    durationicon: "/get-services/ev-tech/smart-home-duration.svg",
    priceicon: "/get-services/ev-tech/smart-home-price.svg",
  },
];
