export const networkWifi = [
  {
    image: "/get-services/network-wifi/ethernet.svg",
    name: "Ethernet/WiFi network support",
    features: [
      "Make sure modem/router/switch is/are connected",
      "Verify configuration and updates",
      "Troubleshoot connectivity issues",
      "Internet speed test",
      "Password and Access recovery",
      "Advise on necessary repair or upgrade",
    ],
    durationicon: "/get-services/network-wifi/ethernet-duration.svg",
    priceicon: "/get-services/network-wifi/ethernet-price.svg",
  },
  {
    image: "/get-services/network-wifi/on-site.svg",
    name: "Cell Signal Boosting",
    features: [
      "Inspection of existing LAN cabling and WiFi coverage",
      "Visual inspection for any potential barriers that may affect the network performance",
      "Identify user arreas",
      "Determine initial wired and wireless access point locations",
      "Document findings",
    ],
    durationicon: "/get-services/network-wifi/on-site-duration.svg",
    priceicon: "/get-services/network-wifi/on-site-price.svg",
  },
  {
    image: "/get-services/network-wifi/cell-signal.svg",
    name: "On-Site Survey",
    features: [
      "Cell signal booster installation for AT&T, Verizon, T-Mobile, US Cellular, and Straight Talk",
      "Determine the closest cell tower location",
      "Determine antennas and other equipment installation location",
      "Aiming outdoor antenna to the best signal level from your carrier",
      "Post-install equipment setup",
      "Dedicated local support",
      "No subscription fees",
      "Quantity discount is available",
    ],
    durationicon: "/get-services/network-wifi/cell-signal-duration.svg",
    priceicon: "/get-services/network-wifi/cell-signal-price.svg",
  },
  {
    image: "/get-services/network-wifi/large-area-wifi.svg",
    name: "Large area WiFi network design",
    features: [
      "Conduct a site survey",
      "Visual inspection for any potential barriers that may affect the network performance",
      "Identify user areas",
      "Locating sites and installing WiFi units",
      "Determining Equipment Needed",
      "Run a predictive survey to estimate expected coverage",
      "Document findings",
    ],
    durationicon: "/get-services/network-wifi/large-area-wifi-duration.svg",
    priceicon: "/get-services/network-wifi/large-area-wifi-price.svg",
  },
  {
    image: "/get-services/network-wifi/smart-wifi.svg",
    name: "Smart WiFi",
    features: [
      "3 Wireless Access Points (APs) Installation",
      "Determine an equipment installation location",
      "Run Internet cable to each AP",
      "Post-install equipment setup",
      "Dedicated local support",
      "No subscription fees",
      "Quantity discount is available",
    ],
    durationicon: "/get-services/network-wifi/smart-wifi-duration.svg",
    priceicon: "/get-services/network-wifi/smart-wifi-price.svg",
  },
  {
    image: "/get-services/network-wifi/smart-wifi.svg",
    name: "Wiring & Prewiring",
    features: [
      "Wire/cable run inside of wall passing one floor",
      "Define wire/cable passway and wall plates location",
      "Provide possible pitfalls before starting a job",
      "Label and terminate the cable",
      "Test connection status",
      "Additional charges may apply to patch the wall/ceiling during the service if any",
      "Quantity discount is available",
    ],
    durationicon: "/get-services/network-wifi/smart-wifi-duration.svg",
    priceicon: "/get-services/network-wifi/smart-wifi-price.svg",
  },
];

export const smartHome = [
  {
    image: "/get-services/smart-home/complete-smart.svg",
    name: "Complete Smart Technology Design",
    features: [
      "Determine the smart home automation system that is best for you",
      "Create your project specification including features and functionality for each part of your residence",
      "Examine built-in smart tech solutions for your renovation or remodeling",
      "Design the smart system to interact with your existing HVAC, lighting, security, internet network, etc and/or upgrade/install to the latest tech",
      "Design cost is deducted from the project cost estimate",
      "LOXONE Smart Automation",
    ],
    durationicon: "/get-services/smart-home/complete-smart-duration.svg",
    priceicon: "/get-services/smart-home/complete-smart-price.svg",
  },
];

export const entertainment = [
  {
    image: "/get-services/entertainment/home-theater.svg",
    name: "Home Theater Room Design",
    features: [
      "On-Site consultation with trained design and tech consultants",
      "Evaluation of your needs",
      "Understand your style and vision",
      "Basic suggestions for improvement",
      "Identify your entertainment",
      "Define the next steps of your project",
      "Design cost is deducted from the project cost estimate",
    ],
    durationicon: "/get-services/entertainment/home-theater-duration.svg",
    priceicon: "/get-services/entertainment/home-theater-price.svg",
  },
  {
    image: "/get-services/entertainment/media-room.svg",
    name: "Media Room Design",
    features: [
      "On-Site consultation with trained design and tech consultants",
      "Evaluation of your needs",
      "Understand your style and vision",
      "Basic suggestions for improvement",
      "Identify your entertainment",
      "Define the next steps of your project",
      "Design cost is deducted from the project cost estimate",
    ],
    durationicon: "/get-services/entertainment/media-room-duration.svg",
    priceicon: "/get-services/entertainment/media-room-price.svg",
  },
  {
    image: "/get-services/entertainment/entertainment-room.svg",
    name: "Entertainment Room Design",
    features: [
      "On-Site consultation with trained design and tech consultants",
      "Evaluation of your needs",
      "Understand your style and vision",
      "Basic suggestions for improvement",
      "Identify your entertainment",
      "Define the next steps of your project",
      "Design cost is deducted from the project cost estimate",
    ],
    durationicon: "/get-services/entertainment/entertainment-room-duration.svg",
    priceicon: "/get-services/entertainment/entertainment-room-price.svg",
  },
  {
    image: "/get-services/entertainment/whole-home.svg",
    name: "Whole Home Audio System Design",
    features: [
      "On-Site consultation with trained design and tech consultants",
      "Evaluation of your needs",
      "Understand your style and vision",
      "Basic suggestions for improvement",
      "Identify your entertainment",
      "Define the next steps of your project",
      "Design cost is deducted from the project cost estimate",
    ],
    durationicon: "/get-services/entertainment/whole-home-duration.svg",
    priceicon: "/get-services/entertainment/whole-home-price.svg",
  },
  {
    image: "/get-services/entertainment/remodeling-design.svg",
    name: "Remodeling Design with built-in tech",
    features: [
      "On-Site consultation with trained design and tech consultants",
      "Evaluation of your needs",
      "Understand your style and vision",
      "Basic suggestions for improvement",
      "Identify your entertainment",
      "Define the next steps of your project",
      "Design cost is deducted from the project cost estimate",
    ],
    durationicon: "/get-services/entertainment/remodeling-duration.svg",
    priceicon: "/get-services/entertainment/remodeling-price.svg",
  },
  {
    image: "/get-services/entertainment/rgbw.svg",
    name: "RGBW design",
    features: [
      "On-Site consultation with trained design and tech consultants",
      "Evaluation of your needs",
      "Understand your style and vision",
      "Basic suggestions for improvement",
      "Identify your entertainment",
      "Define the next steps of your project",
      "Design cost is deducted from the project cost estimate",
    ],
    durationicon: "/get-services/entertainment/rgbw-duration.svg",
    priceicon: "/get-services/entertainment/rgbw-price.svg",
  },
];

export const homeTheater = [
  {
    image: "/get-services/home-theater/home-theater.svg",
    name: "Home Theater and Sound System Setup",
    features: [
      "Connect Video and Audio components in one location",
      "Connect speakers, installation speakers and prewiring is an additional cost",
      "Basic AV settings and Internet/WiFi connectivity setup",
      "Remote setup, universal remote like Logitech Harmony setup is an additional $ 99",
      "Set-up a mobile app if applicable",
    ],
    durationicon: "/get-services/home-theater/home-theater-duration.svg",
    priceicon: "/get-services/home-theater/home-theater-price.svg",
  },
  {
    image: "/get-services/home-theater/on-wall.svg",
    name: "On-wall 5 surround speakers mounting",
    features: [
      "Determine speakers' locations",
      "Mount speakers (speaker wall mounts are not included)",
      "Connect speaker wires to speakers ",
      "On-wall speaker pre-wiring with cord covers is an additional $89 for each speaker (wire and cord covers are not included)",
      "In-wall speaker pre-wiring is an additional $299 per speaker (wire is not included, additional charges may apply to fix trim and finishing)",
    ],
    durationicon: "/get-services/home-theater/on-wall-duration.svg",
    priceicon: "/get-services/home-theater/on-wall-price.svg",
  },
  {
    image: "/get-services/home-theater/on-wall-7.svg",
    name: "On-wall 7 surround speakers mounting",
    features: [
      "Determine speakers' locations",
      "Mount speakers (speaker wall mounts are not included)",
      "Connect speaker wires to speakers ",
      "On-wall speaker pre-wiring with cord covers is an additional $89 for each speaker (wire and cord covers are not included)",
      "In-wall speaker pre-wiring is an additional $299 per speaker (wire is not included, additional charges may apply to fix trim and finishing)",
    ],
    durationicon: "/get-services/home-theater/on-wall-7-duration.svg",
    priceicon: "/get-services/home-theater/on-wall-7-price.svg",
  },
];

export const evTech = [
  {
    image: "/get-services/ev-tech/home-ev.svg",
    name: "Home EV Charger Installation",
    features: [
      "Consultation and Estimation",
      "Get a permit and handle necessary inspections ",
      "Verify your electrical panel can handle your charging station load ",
      "Provide solutions to improve power ampacity",
      "Install circuit breaker, run electrical cable, install EV charger",
      "Verify EV charger operation, completed app setup if applicable",
    ],
    durationicon: "/get-services/ev-tech/home-ev-duration.svg",
    priceicon: "/get-services/ev-tech/home-ev-price.svg",
  },
  {
    image: "/get-services/ev-tech/smart-home.svg",
    name: "Smart Home Ecosystem Design",
    features: [
      "Consultation",
      "Identify the preferences of your complete smart home ecosystem: solar, automation, and your car ",
      "Determine the smart home automation system that is best for you  ",
      "Create your project specification including features and functionality for each part of your residence ",
      "Examine built-in smart tech solutions for your renovation or remodeling",
      "Design the smart system to interact with your existing HVAC, lighting, security, internet network, etc and/or upgrade/install to the latest tech ",
      "Design cost is deducted from the project cost estimate",
    ],
    durationicon: "/get-services/ev-tech/smart-home-duration.svg",
    priceicon: "/get-services/ev-tech/smart-home-price.svg",
  },
];

export const smartDevices = [
  {
    image: "/get-services/smart-devices/video-doorbell.svg",
    name: "Video Doorbell Installation",
    features: [
      "Video doorbell installation with existing functional doorbell or battery powered ",
      "Installation of a chime adapter if applicable",
      "Set-up a mobile app and the camera basic functionality ",
      "Installation and setup of video doorbell compatible wireless chime",
      "Transformer replacement (transformer is included) is an additional $139",
      "Sales tax is subject to additional charges",
    ],
    durationicon: "/get-services/smart-devices/video-doorbell-duration.svg",
    priceicon: "/get-services/smart-devices/video-doorbell-price.svg",
  },
  {
    image: "/get-services/smart-devices/smart-outdoor.svg",
    name: "Smart Outdoor Camera Installation",
    features: [
      "Helping decide a camera location",
      "Install the camera",
      "Set-up a mobile app and the camera basic functionality",
      "This is battery powered camera installation ",
      "Flood light camera replacement with the existing flood light is an additional $39",
      "Solar-powered camera installation is an additional $29 ",
      "USB-powered camera installation is an additional $29",
    ],
    durationicon: "/get-services/smart-devices/smart-outdoor-duration.svg",
    priceicon: "/get-services/smart-devices/smart-outdoor-price.svg",
  },
  {
    image: "/get-services/smart-devices/smart-door.svg",
    name: "Smart Door Lock Installation",
    features: [
      "Installation of a smart lock with an existing door lock",
      "Set-up a mobile app and the smart lock basic functionality",
      "Quantity discount is available",
    ],
    durationicon: "/get-services/smart-devices/smart-door-duration.svg",
    priceicon: "/get-services/smart-devices/smart-door-price.svg",
  },
  {
    image: "/get-services/smart-devices/smart-thermostat.svg",
    name: "Smart Thermostat Installation",
    features: [
      "Installation of smart thermostat with existing thermostat",
      "C-wire add-on is an additional charge between $79 - 199 depending on circumstances ",
      "Set up a mobile app and the thermostat basic functionality",
      "Installation of additional temperature sensor(s) if applicable",
      "Quantity discount is available",
    ],
    durationicon: "/get-services/smart-devices/smart-thermostat-duration.svg",
    priceicon: "/get-services/smart-devices/smart-thermostat-price.svg",
  },
  {
    image: "/get-services/smart-devices/smart-garage.svg",

    name: "Smart Garage Door Opener",
    features: [
      "Replacement with existing garage door opener or new installation (see options while booking) ",
      "Installation of sensors and on-wall control panel ",
      "Garage door opener set-up ",
      "In-car Home Link programming if applicable",
      "Set-up a mobile app if applicable",
      "New garage door opener installations with a garage ceiling up to 9 feet cost an additional $19, up to 12 - $199, up to 15 - $239",
    ],
    durationicon: "/get-services/smart-devices/smart-garage-duration.svg",
    priceicon: "/get-services/smart-devices/smart-garage-price.svg",
  },
  {
    image: "/get-services/smart-devices/other-smart.svg",

    name: "Other Smart Devices Installation",
    features: [
      "Replacement with existing one",
      "Mobile App and device basic functionality setup",
      "Quantity discount is available",
    ],
    durationicon: "/get-services/smart-devices/other-duration.svg",
    priceicon: "/get-services/smart-devices/other-price.svg",
  },
];

export const tvMounting = [
  {
    image: "/get-services/tv-mounting/floating-tv.svg",
    name: "Floating TV Entertainment Center/Stand",
    features: [
      "Assemble and install of one provided floating TV stand or Floating TV entertainment center ",
      "TV basic setup ",
      "Connect all AV devices (AV device(s) setup/re-setup is available for additional cost starting as low as $75)  ",
    ],
    durationicon: "/get-services/tv-mounting/tv-mounting-duration.svg",
    priceicon: "/get-services/tv-mounting/tv-mounting-price.svg",
  },
  {
    image: "/get-services/tv-mounting/frame-tv.svg",
    name: "Frame TV Wall Mounting",
    features: [
      "Assemble and install of one provided floating TV stand or Floating TV entertainment center ",
      "TV basic setup ",
      "Connect all AV devices (AV device(s) setup/re-setup is available for additional cost starting as low as $75)  ",
    ],
    durationicon: "/get-services/tv-mounting/frame-tv-duration.svg",
    priceicon: "/get-services/tv-mounting/frame-tv-price.svg",
  },
  {
    image: "/get-services/tv-mounting/outdoor-tv.svg",
    name: "Outdoor TV Mounting",
    features: [
      "Basic installation of one provided TV wall mount and mount of one TV (custom installation is available and additional cost will be determined after work scope evaluation) ",
      "TV basic setup ",
      "Personalized recommendation for the best TV location, essential parts of your outdoor setup, and combination of your outdoor audio and television setup for your patio, pool, and/or backyard  ",
    ],
    durationicon: "/get-services/tv-mounting/outdoor-tv-duration.svg",
    priceicon: "/get-services/tv-mounting/outdoor-tv-price.svg",
  },
  {
    image: "/get-services/tv-mounting/32.svg",
    name: 'Up to 32" TV Wall Mounting',
    features: [
      "Drywall basic TV Mounting of 1 customer-supplied TV and TV wall mount",
      "Install provided one TV wall mount and mount one TV ",
      "TV basic setup ",
      "Connect all AV devices (AV device(s) setup/re-setup is available for additional cost starting as low as $75)",
    ],
    durationicon: "/get-services/tv-mounting/32-inch-duration.svg",
    priceicon: "/get-services/tv-mounting/32-inch-price.svg",
  },
  {
    image: "/get-services/tv-mounting/33-66.svg",
    name: 'Up to 33"-66" TV Wall Mounting',
    features: [
      "Drywall basic TV wall Mounting",
      "Install provided one TV wall mount and mount one TV ",
      "TV basic setup ",
      "Connect all AV devices (AV device(s) setup/re-setup is available for additional cost starting as low as $99) ",
      "Brick, concrete, over fireplace TV mounting is available for an additional $79 * Ceiling TV mounting is an additional $99 ",
      "Soundbar mounting is an additional $79 ",
      "In-wall cable/wire concealment vertically behind a wall within the same stud passway is an additional $79 or $199 including a concealment kit, no HDMI/AV cables are included. This service doesn't work with over fireplace TV location, an additional estimate needed",
    ],
    durationicon: "/get-services/tv-mounting/33-66inch-duration.svg",
    priceicon: "/get-services/tv-mounting/33-66inch-price.svg",
  },
  {
    image: "/get-services/tv-mounting/70.svg",
    name: '70"+ TV Wall Mounting',
    features: [
      "Drywall basic TV wall Mounting",
      "Install provided one TV wall mount and mount one TV ",
      "TV basic setup ",
      "Connect all AV devices (AV device(s) setup/re-setup is available for additional cost starting as low as $99) ",
      "Brick, concrete, over fireplace TV mounting is available for an additional $79 ",
      "Ceiling TV mounting is an additional $99 ",
      "Soundbar mounting is an additional $79 ",
      "In-wall cable/wire concealment vertically behind a wall within the same stud passway is an additional $79 or $199 including a concealment kit, no HDMI/AV cables are included. This service doesn't work with over fireplace TV location, an additional estimate needed",
    ],
    durationicon: "/get-services/tv-mounting/70inch-duration.svg",
    priceicon: "/get-services/tv-mounting/70inch-price.svg",
  },
];

export const consultation = [
  {
    image: "/get-services/consultation/smart-home.svg",
    name: "Smart Home Automation Consultation",
    features: [
      "On-Site consultation with a trained technician/consultant ",
      "Evaluation of your tech needs  ",
      "Technology advisory ",
      "Basic suggestions for improvement ",
      "Define the next steps of your project",
    ],
    durationicon: "/get-services/consultation/smart-home-duration.svg",
  },
  {
    image: "/get-services/consultation/real-renovation.svg",
    name: "Real Renovation with Built-in Technology",
    features: [
      "On-Site consultation with a trained technician/consultant ",
      "Evaluation of your tech needs  ",
      "Technology advisory ",
      "Basic suggestions for improvement ",
      "Define the next steps of your project",
    ],
    durationicon: "/get-services/consultation/real-renovation-duration.svg",
  },
  {
    image: "/get-services/consultation/audio-video.svg",
    name: "Audio/Video Integration Consultation",
    features: [
      "On-Site consultation with a trained technician/consultant ",
      "Evaluation of your tech needs  ",
      "Technology advisory ",
      "Basic suggestions for improvement ",
      "Define the next steps of your project",
    ],
    durationicon: "/get-services/consultation/audio-video-duration.svg",
  },
  {
    image: "/get-services/consultation/basement-finish.svg",
    name: "Basement Finish-Remodel Consultation",
    features: [
      "On-Site consultation with a trained technician/consultant ",
      "Understand your style and vision ",
      "Evaluation of your tech needs  ",
      "Technology advisory ",
      "Basic suggestions for improvement ",
      "Define the next steps of your project",
    ],
    durationicon: "/get-services/consultation/basement-finish-duration.svg",
  },
  {
    image: "/get-services/consultation/smart-ev.svg",
    name: "Smart EV Charging Consultation",
    features: [
      "On-Site consultation with a trained technician/consultant ",
      "Evaluation of your tech needs  ",
      "Verify your electrical panel can handle your charging station load  ",
      "Technology advisory ",
      "Basic suggestions for improvement ",
      "Define the next steps of your project",
    ],
    durationicon: "/get-services/consultation/smart-ev-duration.svg",
  },
  {
    image: "/get-services/consultation/home-improvement.svg",
    name: "Home Improvement Consultation",
    features: [
      "On-Site consultation with a trained technician/consultant ",
      "Basic suggestions for improvement ",
      "Technology advisory ",
      "Take notes and make an estimate ",
      "Define the next steps of your project",
    ],
    durationicon: "/get-services/consultation/home-improvement-duration.svg",
  },
];

export const support = [
  {
    image: "/get-services/support/warranty-claim.svg",
    name: "Warranty Claim",
    features: [
      "Provide details of your claim ",
      "Include pictures if available ",
      "Set an appointment for evaluation and/or repair/replacement if possible at the same time ",
      "Define the next steps of the issue(s) correction",
    ],
    durationicon: "/get-services/support/support-duration.svg",
  },
  {
    image: "/get-services/support/troubleshooting.svg",
    name: "Troubleshooting Service",
    features: [
      "Understanding the problem ",
      "Basic software/app/device settings verification and adjustments to correct issues if any found ",
      "Diagnosing the root cause ",
      "Providing further suggestions to correct issues due to hardware or wiring malfunction ",
      "Provide an estimate on additional parts and labor cost to correct the problem ",
      "This is up to 1 hour of the troubleshooting service, every additional hour for the service is an additional $89 per hour.",
    ],
    durationicon: "/get-services/support/troubleshooting-duration.svg",
    priceicon: "/get-services/support/troubleshooting-price.svg",
  },
  {
    image: "/get-services/support/electronics.svg",
    name: "Electronics Recycling",
    features: ["Take away electronic devices for recycling"],
    durationicon: "/get-services/support/recycling-duration.svg",
    priceicon: "/get-services/support/recycling-price.svg",
  },
];
