export enum ROUTES {
  HOME = "/",
  SYSTEM_DESIGN = "/system-design",
  NETWORK_SYSTEM = "/network",
  AUDIO_VISUAL_SYSTEMS = "/audio-visual-systems",
  LOXONE_AUTOMATION = "/loxone-automation",
  LOXONE_RESIDENTIAL = "/loxone-residential",
  LOXONE_COMMERCIAL = "/loxone-commercial",
  ENERGY_MANAGEMENT = "/energy-management",
  OUTDOOR_TV = "/outdoor-tv",
  BLOG = "/blog",
  CONSULTATION = "/consultation",
  HIGH_PERFORMANCE_SOUND = "/high-performance-sound",
  GAME_MEDIA = "/game-media",
  CHECKLIST_LONG = "/checklist-long",
  CHECKLIST_SHORT = "/checklist-short",
  HOME_THEATER = "/home-theater",
  HOME_AUDIO = "/home-audio",
  OUTDOOR_ENTERTAINMENT = "/outdoor-entertainment",
}
